<a href="https://colab.research.google.com/github/shaon11579/VAE-2021-/blob/main/VAE_corr_matrix_gen_code_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
from scipy.stats import random_correlation
from scipy.linalg import eigh

In [2]:
##print(random_correlation.rvs([1.5,.5]))
dim = 8
##my_eigs = [1, .5, 1.5, 2, .3, .7, .1, .9, 5, .25, .25,
##           .25, .25, 1, 1, 1.2, .9, .9, .45, 1.55]
#my_eigs = [1.8, .3, .9]
my_eigs = [1, 1, 0.8, 0.9, 1.2, 1.1, 1.05, 0.95]
corr = random_correlation.rvs(my_eigs)
print(corr)
e1, v1 = eigh(corr)
print(e1)

[[ 1.         -0.01385995 -0.02261094 -0.06214653  0.01116029  0.01683477
   0.01707037 -0.03588392]
 [-0.01385995  1.         -0.02919391  0.01481117 -0.00906924 -0.04208801
  -0.01782837 -0.00413132]
 [-0.02261094 -0.02919391  1.          0.05533811 -0.00476264  0.00452804
  -0.03428299  0.04607672]
 [-0.06214653  0.01481117  0.05533811  1.         -0.04788041 -0.02160471
  -0.01376406 -0.03755327]
 [ 0.01116029 -0.00906924 -0.00476264 -0.04788041  1.          0.08589664
   0.01347964  0.00350788]
 [ 0.01683477 -0.04208801  0.00452804 -0.02160471  0.08589664  1.
   0.03179836 -0.15070745]
 [ 0.01707037 -0.01782837 -0.03428299 -0.01376406  0.01347964  0.03179836
   1.          0.02506452]
 [-0.03588392 -0.00413132  0.04607672 -0.03755327  0.00350788 -0.15070745
   0.02506452  1.        ]]
[0.8  0.9  0.95 1.   1.   1.05 1.1  1.2 ]


In [3]:
pos_corr = np.zeros([dim,dim])
for row in range(0, dim):
    for col in range(0, dim):
        pos_corr[row,col] = np.round(abs(corr[row,col]), 3)
        #pos_corr[row,col] = abs(corr[row,col])
print(pos_corr)
e2, v2 = eigh(pos_corr)
print(e2)

[[1.    0.014 0.023 0.062 0.011 0.017 0.017 0.036]
 [0.014 1.    0.029 0.015 0.009 0.042 0.018 0.004]
 [0.023 0.029 1.    0.055 0.005 0.005 0.034 0.046]
 [0.062 0.015 0.055 1.    0.048 0.022 0.014 0.038]
 [0.011 0.009 0.005 0.048 1.    0.086 0.013 0.004]
 [0.017 0.042 0.005 0.022 0.086 1.    0.032 0.151]
 [0.017 0.018 0.034 0.014 0.013 0.032 1.    0.025]
 [0.036 0.004 0.046 0.038 0.004 0.151 0.025 1.   ]]
[0.81717595 0.91356079 0.96906965 0.98163608 1.00331859 1.01430765
 1.05677421 1.24415708]


In [5]:
#np.save('cor3.npy', pos_corr)

# build by hand:
my_matrix = np.array([
    [ 1,.1, 0, 0,.3, 0, 0, 0],
    [.1, 1, 0,.2, 0, 0, 0, 0],
    [ 0, 0, 1, 0, 0, 0, 0, 0],
    [ 0,.2, 0, 1, 0, 0, 0, 0],
    [.3, 0, 0, 0, 1, 0, 0,.2],
    [ 0, 0, 0, 0, 0, 1,.4, 0],
    [ 0, 0, 0, 0, 0,.4, 1, 0],
    [ 0, 0, 0, 0,.2, 0, 0, 1]
    ])
e3, v3 = eigh(my_matrix)
print(my_matrix)
print(my_matrix == np.transpose(my_matrix))
print(e3)
print(np.linalg.det(my_matrix))
np.save('chosen_cor8.npy', my_matrix)

[[1.  0.1 0.  0.  0.3 0.  0.  0. ]
 [0.1 1.  0.  0.2 0.  0.  0.  0. ]
 [0.  0.  1.  0.  0.  0.  0.  0. ]
 [0.  0.2 0.  1.  0.  0.  0.  0. ]
 [0.3 0.  0.  0.  1.  0.  0.  0.2]
 [0.  0.  0.  0.  0.  1.  0.4 0. ]
 [0.  0.  0.  0.  0.  0.4 1.  0. ]
 [0.  0.  0.  0.  0.2 0.  0.  1. ]]
[[ True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True]]
[0.6        0.62583426 0.8        1.         1.         1.2
 1.37416574 1.4       ]
0.6935039999999999


# next data with 300 sample corr matrix 

In [6]:
import numpy as np

num_data = 3000
num_skills = 4
num_items = 27 
discr_range = [0.25, 1.4]
diff_range = [-2,2]
#q_prob = 0.35
sim_theta = np.zeros([num_data, num_skills])

In [7]:

# generate ability parameters
#C = np.genfromtxt('cor_mat_dtmr.csv', delimiter=',', dtype='float32') 
#print(C)
#C[0,0] = 1
#np.save('cor_mat_dtmr.npy', C)
#corr_mat = np.load('C:\\Users\\gconverse\\Desktop\\irt_vae_work_fall_19\\data_generation\\cor_mat_dtmr.npy')
#corr_mat = np.array([[1.0, 0.3, 0.0, 0.0],
#                     [0.3, 1.0, 0.1, 0.0],
#                     [0.0, 0.1, 1.0, 0.2],
#                     [0.0, 0.0, 0.2, 1.0]])
corr_mat = np.array([[1.0, .25, 0.0, .15],
                     [.25, 1.0, 0.0, 0.1],
                     [0.0, 0.0, 1.0, 0.0],
                     [.15, 0.1, 0.0, 1.0]])

print(corr_mat)

[[1.   0.25 0.   0.15]
 [0.25 1.   0.   0.1 ]
 [0.   0.   1.   0.  ]
 [0.15 0.1  0.   1.  ]]


In [8]:
#np.save('../data/dtmr_sim3/chosen_cor4.npy', corr_mat)
cholesky = np.linalg.cholesky(corr_mat)
for i in range(num_data):
    epsilon = np.random.normal(size=num_skills)
    sim_theta[i,:] = np.matmul(cholesky, epsilon)

In [9]:
np.savetxt('/content/drive/MyDrive/15-scene/models/theta_sim_dtmr4.csv', sim_theta, delimiter=',')
print(np.mean(sim_theta[:,0]))
print(np.mean(sim_theta[:,1]))
print(np.mean(sim_theta[:,2]))
print(np.mean(sim_theta[:,3]))


FileNotFoundError: ignored

In [10]:
# generate Q-matrix
#Q = np.random.binomial(1, q_prob, size=[num_skills, num_items])
# # make sure each item tests at least one skill
#for col in range(num_items):
#    if sum(Q[:,col])== 0:
#        rand_ind = np.random.randint(num_skills)
#        Q[rand_ind, col] = 1

# Load Q-matrix from fraction4 (in CDM package)
#Q = np.transpose(np.genfromtxt('../fraction4_q_matrix.csv', delimiter=','))
#print("Q from CDM package")
#print(Q)

# Load custom made Q-matrix with simple items 
Q = np.genfromtxt('../q_custom_4_27.csv', delimiter=',', dtype = 'float32')
Q[0,0] = 1 # this is nan for some reason
print("Custom Q:")
print(Q)


OSError: ignored

In [ ]:
# # generate discrimination/difficulty parameters
# # need to consider good MDISC_i and MDIFF_i
sim_discr = np.random.uniform(discr_range[0], discr_range[1], size = [num_skills, num_items])
sim_discr = sim_discr * Q # elementwise mult to make a_ij = 0 iff q_ij = 0
sim_diff = np.random.uniform(diff_range[0], diff_range[1], size = num_items)

print(sim_discr)
print("***")
print(sim_diff)
print(sim_theta[0:5,:])

In [ ]:
#np.savetxt('C:\\Users\\gconverse\\Desktop\\irt_vae_work_fall_19\\data\\chosen_q3\\fraction4_Q.csv', Q, delimiter=',')
np.savetxt('C:\\Users\\gconverse\\Desktop\\irt_vae_work_fall_19\\data\\dtmr_sim4\\disc_sim_dtmr4.csv', sim_discr, delimiter=',')
np.savetxt('C:\\Users\\gconverse\\Desktop\\irt_vae_work_fall_19\\data\\dtmr_sim4\\diff_sim_dtmr4.csv', sim_diff, delimiter=',')
for i in range(num_items):
    sum = 0
    for k in range(num_skills):
        sum += sim_discr[k,i] ** 2
    print(np.math.sqrt(sum))

# 50000, 20 lt and 20 items 

In [ ]:

import numpy as np

num_data = 50000
num_skills = 20
num_items = 200
data_dir = '.\\..\\data\\dtmr_sim200\\'

theta = np.loadtxt(data_dir+'sim_theta_'+str(num_skills)+
                   'skills_size'+str(num_data)+'.csv', delimiter=',')
discr = np.loadtxt(data_dir+'sim_discr_'+str(num_skills)+
                    'skills_'+str(num_items)+'items.csv', delimiter=',')
diff = np.loadtxt(data_dir+'sim_diff_'+str(num_items)+
                   'items.csv', delimiter=',')

probs = np.zeros([num_data, num_items])
responses = np.zeros([num_data, num_items])
for i in range(num_items):
    for j in range(num_data):
        my_sum = np.dot(discr[:,i], theta[j,:])
        this_prob = 1/(1 + np.exp(-my_sum - diff[i]))
        probs[j,i] = this_prob
        responses[j,i] = np.random.binomial(1, this_prob)
print(np.mean(theta))
print(np.mean(probs))
print(np.mean(responses))
print(probs[0:5,:])
print(responses[0:5,:])
np.savetxt(data_dir+'sim_probs_dtmr4.csv', probs, delimiter=',')
np.savetxt(data_dir+'sim_responses_dtmr4.csv', responses, delimiter=',')